### ISSUE TITLE
It is necessary to remove cookies when restarting the ui

### ISSUE THREAD

**Issue by sauljabin** [littlehorse-enterprises/lh-user-tasks#1]
Is it possible to make it more resilient? It is going to be a problem if the user has to remove cookies to make it run.

![image](https://github.com/user-attachments/assets/5138f16d-58ed-4d5f-bb35-7adba44f94e7)

![image](https://github.com/user-attachments/assets/b66082b0-6374-4947-939f-a976b8d476d8)

I usually open incognito to make it run:
![image](https://github.com/user-attachments/assets/66a829bd-1e38-44c3-a678-04a382378897)
![image](https://github.com/user-attachments/assets/608711dc-405a-4a5a-bd8b-b8422f930c68)

**Comment by sauljabin** [comment]
> After discussing with @mijailr he will check if this is an issue on the dashboard because we don't do anything special there either.
> 
> If it is a issue on the dashboard then this will be an issue for all frontend projects that use next-auth and keycloak (i.e. cloud console)
> 
> If not we will just copy the code used on dashboard here

Were you able to replicate it? or it is jut me?

**Comment by HazimAr** [comment]
@sauljabin Yes I was able to replicate it.

**Comment by HazimAr** [comment]
I was able to get but it only works locally, it breaks on docker, not sure if there is some problem with docker or if its the UI.
https://github.com/littlehorse-enterprises/lh-user-tasks/pull/17

There is no backend logs when visiting the UI It seems like there might be some networking issue?
