### ISSUE TITLE
Run api pipeline when merging to main branch

### ISSUE THREAD

**Issue by sauljabin** [littlehorse-enterprises/lh-user-tasks#2]
## Context

We are building the standalone image in the https://github.com/littlehorse-enterprises/lh-user-tasks-api repository. Sometimes this image is behind the latest UI version. 

We need a way to trigger the API pipeline when merging to the main branch.

This is the pipeline that has to be triggered https://github.com/littlehorse-enterprises/lh-user-tasks-api/blob/main/.github/workflows/main.yml

**Comment by HazimAr** [comment]
4c3f575475c66bea9a294bafcfec0accd11a34db fixes this and the PR will modify it
