### ISSUE TITLE
Use LH node base image

### ISSUE THREAD

**Issue by sauljabin** [littlehorse-enterprises/lh-user-tasks#23]
Currently we are using a node vanilla base image in our docker UT image https://github.com/littlehorse-enterprises/lh-user-tasks/blob/main/Dockerfile#L1

To enable TLS we should use nginx, we have create a base image for that https://github.com/littlehorse-enterprises/alpine-nginx-nodejs

nginx configuration here https://github.com/littlehorse-enterprises/alpine-nginx-nodejs/blob/main/nginx.conf

Goal
Adapt our UT image to use the LH base image

**Comment by HazimAr** [comment]
The problem with this is we need the base image to act in a way that its agnostic whether we use a mono repo or not. 

We can try to fit the current Next Build to fit into the base image mold but I would not recommend that and instead recommend having a more agnostic image.

**Comment by sauljabin** [comment]
Well it is the one that the dashboard is using https://github.com/littlehorse-enterprises/littlehorse/blob/master/docker/dashboard/Dockerfile#L1

If it is well parameterized it is good, a lot of services (keycloak for example) provide embedded TLS solutions. Let's have further discussions with @mijailr

**Comment by HazimAr** [comment]
@sauljabin The dashboard doesn't use npm workspaces so when building with next it does not treat it like a monorepo.

Because we have a package that is being used in the dashboard next is building it in 2 subdirectories instead of the root directory.

Lets connect with @mijailr for a possible solution.

**Comment by sauljabin** [comment]
> @sauljabin The dashboard doesn't use npm workspaces so when building with next it does not treat it like a monorepo.
> 
> Because we have a package that is being used in the dashboard next is building it in 2 subdirectories instead of the root directory.
> 
> Lets connect with @mijailr for a possible solution.

Got it, in that case we can copy most of the configurations into this repo and customize it for it
